In [14]:
from skimage.morphology import square, disk
import numpy as np

def custom_kernel2D(radius, shape="square"):
    """
    Create a 2D kernel with a specified shape using skimage's structuring elements.
    The kernel will contain values of 1 for the structuring element and -1 for the background.
    
    Parameters:
        radius (int): The number of pixels the kernel would affect in one direction
                      during erosion or dilation (radius of the structuring element).
        shape (str): The shape of the kernel. Options are "square", "circle", 
                     "vertical_line", "horizontal_line", or "cross".
    
    Returns:
        np.ndarray: A 2D kernel with int32 dtype and contiguous memory.
    """
    if radius < 0:
        raise ValueError("Radius must be a non-negative integer.")
    if shape not in {"square", "circle", "vertical_line", "horizontal_line", "cross"}:
        raise ValueError("Shape must be one of 'square', 'circle', 'vertical_line', 'horizontal_line', or 'cross'.")
    
    # Calculate size as 2 * radius + 1 to ensure odd dimensions
    size = 2 * radius + 1
    
    # Create a background filled with -1
    kernel_2d = -np.ones((size, size), dtype=np.int32)
    
    if shape == "square":
        kernel_2d = np.ones((size, size), dtype=np.int32)  # All 1's for square
    elif shape == "circle":
        disk_mask = disk(radius)
        kernel_2d[disk_mask > 0] = 1
    elif shape == "vertical_line":
        kernel_2d[:, size // 2] = 1  # Vertical line through the center
    elif shape == "horizontal_line":
        kernel_2d[size // 2, :] = 1  # Horizontal line through the center
    elif shape == "cross":
        kernel_2d[:, size // 2] = 1  # Vertical line
        kernel_2d[size // 2, :] = 1  # Horizontal line
    
    # Ensure memory contiguity
    kernel_2d = np.ascontiguousarray(kernel_2d)
    return kernel_2d

# Example usage
square_kernel = custom_kernel2D(1, shape="square")
circle_kernel = custom_kernel2D(1, shape="circle")
vertical_line_kernel = custom_kernel2D(1, shape="vertical_line")
horizontal_line_kernel = custom_kernel2D(1, shape="horizontal_line")
cross_kernel = custom_kernel2D(1, shape="cross")

print("Square Kernel:\n", square_kernel)
print("Circle Kernel:\n", circle_kernel)
print("Vertical Line Kernel:\n", vertical_line_kernel)
print("Horizontal Line Kernel:\n", horizontal_line_kernel)
print("Cross Kernel:\n", cross_kernel)

Square Kernel:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Circle Kernel:
 [[-1  1 -1]
 [ 1  1  1]
 [-1  1 -1]]
Vertical Line Kernel:
 [[-1  1 -1]
 [-1  1 -1]
 [-1  1 -1]]
Horizontal Line Kernel:
 [[-1 -1 -1]
 [ 1  1  1]
 [-1 -1 -1]]
Cross Kernel:
 [[-1  1 -1]
 [ 1  1  1]
 [-1  1 -1]]


In [11]:
import matplotlib.pyplot as plt

def plot_kernel3D(kernel):
    """
    Visualize a 3D kernel with white for 1 and black for 0.
    
    Parameters:
        kernel (np.ndarray): The 3D kernel to visualize.
    """
    if kernel.ndim != 3:
        raise ValueError("The kernel must be a 3D array.")
    
    num_slices = kernel.shape[0]
    fig, axes = plt.subplots(1, num_slices, figsize=(4 * num_slices, 4))
    if num_slices == 1:  # Handle case for a single slice
        axes = [axes]
    
    for i, ax in enumerate(axes):
        ax.imshow(kernel[i], cmap='gray', interpolation='nearest')
        ax.set_title(f"Slice {i+1}")
        ax.axis('off')
    
    plt.tight_layout()
    plt.show()

# Example usage
kernel = custom_kernel2D(2, shape="circle")
